[package]
name = "invaders"
version = "0.1.0"
authors = ["Edson Cabral <e2cabraljunior@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.18.2"
rusty_audio = "1.1.4"
rusty_time ="0.11.0"
